name: Check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
#        python-version: ['3.10']

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
#    - name: Set up Python 3.10
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
#        python-version: "3.10"
        python-version: ${{ matrix.python-version }}
#    - name: Install tox-gh
#      run: python -m pip install tox-gh
#    - name: Setup test suite
#      run: tox4 r -vv --notest
#    - name: Run test suite
#      run: tox4 r --skip-pkg-install
#      env:
#        PYTEST_ADDOPTS: "-vv --durations=10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test tox itself
      run: tox -r -vv --notest
    - name: Test with tox
      run: tox r -vvvv 