name: Coveralls

on:
  - push
  - pull_request

jobs:
  coveralls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Cache pip
#        uses: actions/cache@v2
#        with:
#          path: ~/.cache/pip
#          key: v1-pip-${{ runner.os }}-${{ matrix.python-version }}
#          restore-keys: |
#            v1-pip-${{ runner.os }}
#            v1-pip-
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-${{ matrix.python-version }}
      - name: Install Coveralls
        run: pip install coveralls
      - name: Run Coveralls
        run: coveralls
        env:
          # Note: Set service name to work around
          # https://github.com/TheKevJames/coveralls-python/issues/252
          COVERALLS_SERVICE_NAME: github
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    name: Coveralls Completed
    needs: coveralls
    runs-on: ubuntu-latest
    container:
      image: thekevjames/coveralls
    steps:
      - name: Coveralls Finish
        run: coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}