name: Docker test, build, and (optionally) push

on:
  push:
    branches:
      - main
      - "*"
  release:
    types:
      - published
  schedule:
    - cron: "15 3 * * 6"

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set platform tag
        id: set-platform-tag
        run: |
          echo "PLATFORM_TAG=$(echo ${{ matrix.platform }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: hubuum:${{ env.PLATFORM_TAG }}-testing
          build-args: |
            ENVIRONMENT=testing
          load: true

      - name: Save Docker images as artifacts
        run: |
          docker save hubuum:${{ env.PLATFORM_TAG }} | gzip > hubuum-${{ env.PLATFORM_TAG }}.tar.gz
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: hubuum-${{ env.PLATFORM_TAG }}
          path: hubuum-${{ env.PLATFORM_TAG }}.tar.gz

  test-images:
    needs: build-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      HUBUUM_DATABASE_USER: postgres
      HUBUUM_DATABASE_PASSWORD: postgres
      HUBUUM_DATABASE_NAME: github_actions

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set platform tag
        id: set-platform-tag
        run: |
          echo "PLATFORM_TAG=$(echo ${{ matrix.platform }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: hubuum-${{ env.PLATFORM_TAG }}
          path: hubuum-${{ env.PLATFORM_TAG }}.tar.gz
      - name: Load Docker image from artifact
        run: |
          gzip -d hubuum-${{ env.PLATFORM_TAG }}.tar.gz
          docker load < hubuum-${{ env.PLATFORM_TAG }}.tar

      - name: Run tests
        run: docker run -e MODE=testing hubuum:${{ env.PLATFORM_TAG }}-testing

  push-images:
    needs: test-images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: terjekv
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: terjekv
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            terjekv/hubuum
            ghcr.io/terjekv/hubuum
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},value=latest
            type=raw,value=develop,enable=${{ endsWith(GitHub.ref, 'refs/heads/main') }}

      - name: Rebuild Docker images without testing environment
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          load: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
